services:
  mysql:
    image: mysql:8.0
    container_name: webshop_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: webshop_jager
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
